### PR TITLE
My branch / login features

### PR DESCRIPTION
**Pull request by deanthonymiller**

### CODE REVIEW

**Review by bjpennington — DISMISSED** [review]
Looks great--thanks for taking care of this, Miller!

**Review by dannyyaaj — DISMISSED** [review]

**Review by bjpennington — APPROVED** [review]
should be fine

**Review by dannyyaaj — APPROVED** [review]
everything looks correct now

**Review by Petecoj — APPROVED** [review]
Sweet job Danny!

**Pull request merged**
