### PR TITLE
registration functionality works

### PR DESCRIPTION
**Pull request by dannyyaaj**

### CODE REVIEW

**Review by bjpennington — DISMISSED** [review]
Hot stuff

**Review by Petecoj — DISMISSED** [review]
sweet

**Comment by bjpennington** [comment]
Had to resolve a merge conflict, so I think this needs to be reviewed again

**Review by deanthonymiller — APPROVED** [review]

**Review by Petecoj — APPROVED** [review]
nice merge conflict Bj!

**Pull request merged**
